title: 广工问答
result: flag{}
report: https://reqbin.rkmiao.eu.org/adctf-2025-gdutqa-f078483982/access
problems:
  - id: 2d7b4a6b-a01b-427a-b188-d84c38affa7f
    question: "你知道 **首届广东工业大学网络安全技能大赛** 是什么时候举行的吗？请写出其 **正式比赛的开始时间和结束时间**。（开始时间和结束时间之间 **使用短横线 `-` 进行连接**，时间格式为 `YYYYmmddHHMM`，格式示例: `202507211145-202507211919`）"
    validation: '\d{12}-\d{12}'
    answers: ["202412070900-202412071830"]
  - id: 94c7e0e5-ff1c-4e7b-90e4-837d9da96ed2
    question: "广东工业大学曾经的校园共享自行车服务提供商是 **哈啰**，被称作 **“哈啰工业大学”**（简称 **“哈工大”**），而现在校园共享自行车的业务被 **“美团单车”** 所包揽，~~也自然成为了 **“美团工业大学”**（简称 **“美工大”**）~~。那么你知道 **广东工业大学保卫处** 是什么时候与 **“美团单车”** 以谈判比选方式 **成交共享自行车服务项目** 的吗？请写出 **成交日期**。（日期格式为 `YYYYmmdd`，格式示例: `20250815`）\n\n
    ![](https://pic1.imgdb.cn/item/69211e943203f7be001e03fa.webp)"
    validation: '\d{8}'
    answers: ["20240118"]
  - id: 03f773cb-d7e6-4b6f-9a6f-72c9b2ee6375
    question: "你知道 **广东工业大学图书馆** 所使用的 **书目检索系统** 是什么吗？请写出 **其系统名称及版本号**。（系统名称和版本号之间用 **空格隔开**，系统名称之间的 **空格使用短横线 `-` 连接**，格式示例: `Awesome-Library-Management-System 1.0`）"
    validation: '\S+ \d+(\.\d+(\.\d+)?)?'
    answers: ["SULCMIS-OPAC 4.01"]
  - id: aff4161b-cd62-4760-8075-0f135c0bd166
    question: "“激情全运会，活力大湾区”。你知道广东工业大学 **（非志愿者）有多少名学生以及有多少名老师** 参加了 **全运会** 吗？请分别写出 **参与学生人数和参与老师人数**。（两者之间使用空格分隔开，格式示例: `11 4`）\n\n
    ![](https://pic1.imgdb.cn/item/69211e943203f7be001e03f7.webp)\n\n
    ~~（白切鸡和玫瑰豉油鸡）~~"
    validation: '\d+ \d+'
    answers: ["9 4"]
